services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    volumes:
      - .:/app  # Mount the local directory to the container to allow code changes
    depends_on:
      - redis

  # Redis service for Celery to use as a broker
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  # Celery worker service
  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks.celery worker --loglevel=info
    depends_on:
      - redis
      - app

